fdfs:
  # tracker-server列表
  trackerList:
    - 192.168.0.7:22122
    - 192.168.0.8:22122
  # web服务器，但是没看懂在项目中的作用
  webServerUrl: localhost:8888
  # 连接超时时间
  connect-timeout: 2000
  # 读取超时时间
  so-timeout: 3000
  # 缩略图配置
  thumb-image:
    width: 150
    height: 150
  # 连接池配置
  pool:
    # 从池中借出的对象的最大数目（配置为-1表示不限制）
    max-total: -1
    # 获取连接时的最大等待毫秒数(默认配置为5秒)
    max-wait-millis: 5000
    # 每个key最大连接数
    max-total-per-key: 300
    # 每个key对应的连接池最大空闲连接数
    max-idle-per-key: 10
    # 每个key对应的连接池最小空闲连接数
    min-idle-per-key: 5
