<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>ddf-common</artifactId>
        <groupId>com.ddf.common</groupId>
        <version>boot3.5-2025.1-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>ddf-common-limit</artifactId>
    <version>boot3.5-2025.1-SNAPSHOT</version>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.ddf.common</groupId>
            <artifactId>ddf-common-mvc</artifactId>
            <version>boot3.5-2025.1-SNAPSHOT</version>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>com.ddf.common</groupId>
            <artifactId>ddf-common-authentication</artifactId>
            <version>boot3.5-2025.1-SNAPSHOT</version>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>com.ddf.common</groupId>
            <artifactId>ddf-common-redis</artifactId>
            <version>boot3.5-2025.1-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
    </dependencies>

</project>

