networks:
  middleware-network:
    external: true  # 使用已创建的外部网络

services:
  mysql:
    image: mysql:8.0.32
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      # 显式指定时区，防止 Java 应用读取时间不一致
      TZ: Asia/Shanghai
    # 兼容老版本的mysql客户端，因mysql8以上版本的密码规则导致无法连接
    # command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mysql/data:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql
      # - ./mysql:/var/lib/mysql
      # 挂载到conf.d下，避免文件权限导致配置不生效
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      # 这个是为了同时启动nacos
      # - ./nacos/mysql-init:/docker-entrypoint-initdb.d/
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    healthcheck:
      # 优化：避免在进程列表中泄露密码，利用内置 ping 命令
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - middleware-network

  redis:
    image: redis:6.0.17
    container_name: redis
    restart: always
    command: [ "redis-server", "/data/redis.conf" ]
    ports:
      - "6379:6379"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - middleware-network

  zookeeper:
    image: zookeeper:3.6.4
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zookeeper/conf:/conf
      - ./zookeeper/data:/data
      - ./zookeeper/datalog:/datalog
    healthcheck:
      test: [ "CMD-SHELL", "zkServer.sh status || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - middleware-network
  mongo:
    # 虚拟机器需要在设置 → 系统 → 处理器 → 勾选 "启用 VT-x/AMD-V", 不然只能使用低版本
    # image: mongo:6.0.4
    image: mongo:4.4
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mongo/configdb:/data/configdb
      - ./mongo/db:/data/db
    command: [ "mongod", "--config", "/data/configdb/mongod.conf" ]
    healthcheck:
      test: [ "CMD-SHELL", "mongosh --eval \"db.adminCommand('ping')\"" ]
      interval: 15s
      timeout: 5s
      retries: 5
    networks:
      - middleware-network

  elasticsearch:
    image: elasticsearch:7.17.9
    container_name: es
    restart: always
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # 启动可能会报错，java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
      # 手动执行下权限，es镜像内部以elasticsearch用户， uid通常为1000运行，所以可以在宿主机执行，给挂载目录权限。sudo chown -R 1000:1000 ./elasticsearch/data
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
      - ./elasticsearch/config:/usr/share/elasticsearch/config
    networks:
      - middleware-network

  rocketmq-namesrv:
    image: apache/rocketmq:5.3.2
    container_name: rocketmq-namesrv
    restart: always
    ports:
      - "9876:9876"
    environment:
      - JAVA_OPT_EXT=-Xms256m -Xmx256m
    volumes:
      - ./rocketmq/namesrv/logs:/home/rocketmq/rocketmq-5.3.2/logs
      - ./rocketmq/namesrv/store:/home/rocketmq/rocketmq-5.3.2/store
    command: sh mqnamesrv
    healthcheck:
      test: [ "CMD-SHELL", "timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/9876' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - middleware-network

  rocketmq-broker:
    image: apache/rocketmq:5.3.2
    container_name: rocketmq-broker
    restart: always
    depends_on:
      rocketmq-namesrv:
        condition: service_healthy
    ports:
      - "10909:10909"
      - "10911:10911"
      - "10912:10912"
    environment:
      - NAMESRV_ADDR=rocketmq-namesrv:9876
      - JAVA_OPT_EXT=-Xms256m -Xmx256m
    volumes:
      - ./rocketmq/broker/logs:/home/rocketmq/rocketmq-5.3.2/logs
      - ./rocketmq/broker/store:/home/rocketmq/rocketmq-5.3.2/store
      - ./rocketmq/broker/conf:/home/rocketmq/rocketmq-5.3.2/conf
    command: sh mqbroker -n rocketmq-namesrv:9876 -c /home/rocketmq/rocketmq-5.3.2/conf/broker.conf
    # command: sh mqbroker -n rocketmq-namesrv:9876
    healthcheck:
      test: [ "CMD-SHELL", "timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/10911' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - middleware-network

  rocketmq-proxy:
    image: apache/rocketmq:5.3.2
    container_name: rocketmq-proxy
    restart: always
    depends_on:
      rocketmq-namesrv:
        condition: service_healthy
      rocketmq-broker:
        condition: service_healthy
    ports:
      - "8081:8081"
      - "10901:10901"
      - "10902:10902"
    environment:
      - NAMESRV_ADDR=rocketmq-namesrv:9876
      - JAVA_OPT_EXT=-Xms256m -Xmx256m
    command: sh mqproxy
    healthcheck:
      test: [ "CMD-SHELL", "timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/8081' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - middleware-network

  rocketmq-dashboard:
    image: apacherocketmq/rocketmq-dashboard:2.1.0
    container_name: rocketmq-dashboard
    restart: always
    ports:
      - "8803:8082"
    environment:
      - JAVA_OPTS=-Xmx256m -Xms128m
      - ROCKETMQ_CONFIG_NAMESRVADDR=rocketmq-namesrv:9876
    depends_on:
      - rocketmq-namesrv
    networks:
      - middleware-network

  xxl-job-admin:
    image: xuxueli/xxl-job-admin:3.3.0
    container_name: xxl-job-admin
    restart: always
    ports:
      - "8802:8080"
    volumes:
      - ./xxl-job:/data/applogs
    environment:
      JAVA_OPTS: "-Xms256M -Xmx512M"
      PARAMS: "--spring.datasource.url=jdbc:mysql://mysql:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai --spring.datasource.username=root --spring.datasource.password=${MYSQL_ROOT_PASSWORD} --xxl.job.accessToken=${XXL_JOB_TOKEN}"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - middleware-network

  emqx:
    # 企业版需要license授权， 生产环境只能单机使用
    # image: emqx/emqx-enterprise:5.10.0
    # 可使用5.9版本以前的开源版本，还不是BSL协议，然后自己搭建集群
    image: emqx:5.8.8
    user: "1000:1000"
    container_name: emqx
    restart: always
    ports:
      - "11883:1883"
      - "18083:8083"
      - "18084:8084"
      - "18883:8883"
      - "19083:18083"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./emqx/data:/opt/emqx/data
      - ./emqx/log:/opt/emqx/log
    environment:
      - "EMQX_NODE_NAME=emqx@node1.emqx.com"
      - "EMQX_ADMIN_PASSWORD=${EMQX_PASS}"
    healthcheck:
      test: [ "CMD", "/opt/emqx/bin/emqx", "ctl", "status" ]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      middleware-network:
        aliases:
          - node1.emqx.com

  nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos-standalone-mysql
    env_file:
      - ./nacos/nacos-standalone-mysql.env
    volumes:
      - ./nacos/logs/:/home/nacos/logs
    ports:
      - "8801:8080"
      - "8848:8848"
      - "9848:9848"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    networks:
      - middleware-network
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/snippets:/etc/nginx/snippets:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/log:/var/log/nginx
      - ./nginx/html:/usr/share/nginx/html:ro
    networks:
      - middleware-network
    healthcheck:
      # 这里的 /health 记得在 nginx 配置里加上，否则会一直显示 unhealthy
      test: [ "CMD-SHELL", "wget -q -O - http://127.0.0.1/manager/health || exit 1" ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    ulimits:
      nofile:
        soft: 200000
        hard: 200000
