server:
  port: 8080
  tomcat:
    max-connections: 20000
    max-threads: 400
    min-spare-threads: 20
spring:
  jackson:
    time-zone: GMT+8
    default-property-inclusion: ALWAYS
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
  datasource:
    initialization-mode: ALWAYS
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      url: jdbc:p6spy:mysql://localhost:3306/boot-quick?characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
      initial-size: 3
      max-active: 15
      min-idle: 3
      max-wait: 5000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      poolPreparedStatements: true
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 3000
      max-open-prepared-statements: 20
      async-init: true

  messages:
    basename: exception/exception
    use-code-as-default-message: true

  #  redis:
  #    cluster:
  #      max-redirects: 3
  #      nodes: localhost:6601,localhost:6602,localhost:6603
  #    database: 0
  #    jedis:
  #      pool:
  #        max-active: 100
  #        max-idle: 10
  #        min-idle: 0
  #        max-wait: 800ms
  #    timeout: 1000ms


  mail:
    username: 1041765757@qq.com                # 用来验证授权的邮件用户名
    password: gotartrfwuytbcji                # 根据QQ邮箱设置-账户里生成的第三方登陆授权码，可用来代替密码登陆
    host: smtp.qq.com                         # 邮件服务器类型
    properties.mail.smtp.ssl.enable: true # 用以支持授权码登陆

#  rabbitmq:
#    addresses: localhost:5672
#    username: root
#    password: password
#    virtual-host: / # 创建的虚拟主机，可以简单理解为一个实例，所有队列交换器路由等都是在它的基础上，默认为/，最好自己新建一个
#    publisher-confirms: true # 消息被投递之后如何确保一定被正确投递或消费，开启conform模式
#    listener:
#      direct:
#        acknowledge-mode: manual  # 开启手动ack
#      simple:
#        acknowledge-mode: manual # 开启手动ack
#        retry:
#          enabled: false
#          max-attempts: 3
#          initial-interval: 3000 # 第一次和第二次尝试传递消息之间的持续时间
#        default-requeue-rejected: false


customs:  # 自定义的属性最好都写在custom前缀下，方便辨认
  global-properties:
    snowflakeWorkerId: 1      # worker Id can't be greater than 31 or less than 0
    snowflakeDataCenterId: 1  # dataCenterId Id can't be greater than 31 or less than 0
    ignoreErrorTraceProfile:  # 过滤将异常堆栈信息输出打前端接口返回值的环境
      - local
      - default
  jwt:
    secret: woshiyigefenshuajiangfenshuabenlingqiang
    expiredMinute: 1080
    refreshTokenMinute: 10
    ignores:
      - path: /**


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  mapper-locations: classpath:mapper/*.xml


logging:
  level:
    com.ddf.boot.quick.mapper: debug

management:
  health:
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
    jolokia:
      enabled: true