user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    use epoll;
	worker_connections 65535;
	multi_accept on;
}


http {
    charset utf-8;
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
	include /etc/nginx/conf.d/*.conf;
    proxy_set_header              X-Scheme $scheme;
    # 表示客户端真实的协议（http还是https）
    proxy_set_header              X-Forwarded-Proto $scheme;
    proxy_redirect                off;
    # 保留代理之前的host 包含客户端真实的域名和端口号
    proxy_set_header              Host $host;
    # 保留代理之前的真实客户端ip
    proxy_set_header              X-Real-IP $remote_addr;
    # 这个Header和X-Real-IP类似，但它在多级代理时会包含真实客户端及中间每个代理服务器的IP
    proxy_set_header              X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header              Server_Addr $server_addr;
    proxy_set_header              Server_Name $server_name;

    # 项目如果支持websocket 需要在下面的location下配置请求头
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    # 不定制化的格式
    # log_format  simple_main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    # 定制化的格式，按需决定是否需要后续自定义的请求参数字段， 实例"$http_token" "$http_ncode" "$http_os"
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for" "$http_imei"
                      "$http_token" "$http_ncode" "$http_os" "$http_reqtime"
                      "$upstream_addr" "$upstream_status" "$upstream_response_time"';

    access_log /var/log/nginx/access.log main buffer=256k flush=1s;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;

    keepalive_timeout 15s;
    keepalive_requests 1000;
    client_header_timeout 10s;
    client_body_timeout 15s;
    send_timeout 30s;
    client_max_body_size 20m;
    client_body_buffer_size 256k;
    types_hash_max_size 4096;
    # 隐藏Nginx服务器版本
    server_tokens off;

	gzip on;
	gzip_comp_level 5;
	gzip_min_length 1024;
	gzip_proxied any;
	gzip_vary on;
	gzip_types
		text/plain
		text/css
		text/xml
		application/json
		application/javascript
		application/xml
		application/rss+xml
		image/svg+xml;

    server {
        # Nginx 找不到任何一个 server_name 与请求的域名匹配时，就会把这个请求交给带有 default_server 标记的 server 块来处理
        listen 80 default_server;
        # 匹配所有域名
        server_name _;

        location /health {
            access_log off;
            return 200 "OK";
        }

        # 其他未定义域名的请求直接拒绝，防止恶意扫描
        location / {
            return 444;
        }
    }
}
