customs:
  jwt:
    secret: Hello world, Hello everyone!
    permitAllIgnores:
      - path: /v2/*
      - path: /swagger-ui.html
      - path: /swagger-ui.html/*
      - path: /swagger-resources/**
      - path: /swagger/**
      - path: /webjars/**
      - path: /druid/**
      - path: /csrf
      - path: /js/*