<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.ddf.common</groupId>
        <artifactId>ddf-common</artifactId>
        <version>1.0.1-jdk17-SNAPSHOT</version>
    </parent>

    <artifactId>ddf-common-alarm</artifactId>
    <version>1.0.1-jdk17-SNAPSHOT</version>
    <name>ddf-common-api</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <alibaba-dingtalk.version>2.0.0</alibaba-dingtalk.version>
    </properties>


    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.aliyun</groupId>
            <artifactId>alibaba-dingtalk-service-sdk</artifactId>
            <version>${alibaba-dingtalk.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-context</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ddf.common</groupId>
            <artifactId>ddf-common-core</artifactId>
            <version>1.0.1-jdk17-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.ddf.common</groupId>
            <artifactId>ddf-common-redis</artifactId>
            <version>1.0.1-jdk17-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>

</project>
