<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>ddf-common</artifactId>
        <groupId>io.github.dongfangding</groupId>
        <version>boot3.5-2025.1-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>ddf-common-zookeeper</artifactId>
    <version>boot3.5-2025.1-SNAPSHOT</version>
    <description>zk使用相关工具</description>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <curator.version>5.1.0</curator.version>
    </properties>


    <dependencies>
        <dependency>
            <groupId>io.github.dongfangding</groupId>
            <artifactId>ddf-common-core</artifactId>
            <version>boot3.5-2025.1-SNAPSHOT</version>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>io.github.dongfangding</groupId>
            <artifactId>ddf-common-distributed-lock</artifactId>
            <version>boot3.5-2025.1-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>

    </dependencies>
</project>

