# 还有一种将ids单独做成一个服务， 提供内部调用，这样就可以在一个服务里去处理与全局id相关的事情


## 使用starter的模式，一个是将ids单独做成也给服务， 则系统只要参考官方自己的starter的写法注入SnowflakeService即可
#   com.sankuai.inf.leaf.plugin.LeafSpringBootStarterAutoConfigure
leaf:
  name: com.sankuai.leaf.opensource.snowflake
  segment:
    enable: false
  snowflake:
    enable: true
    address: ${leaf.snowflake.address}
    port: ${leaf.snowflake.port}