customs:
  jwt:
    secret: WoshiyigefenshuajiangfenshuabenlingqiangwoyaobanaxinfangzishuadegengpiaoliangshualefangziyoushuangqiangaiyawodexiaobizibianyabianleYang
    permitAllIgnores:
      - path: /v2/*
      - path: /swagger-ui.html
      - path: /swagger-ui.html/*
      - path: /swagger-resources/**
      - path: /swagger/**
      - path: /webjars/**
      - path: /druid/**
      - path: /csrf
      - path: /app.js
      - path: /index.html
      - path: /websocket.html
      - path: /js/*
      - path: /ws/*
      - path: /pay-ws/*
      - path: /heartCheck.txt